### ISSUE TITLE
Updates needed for post-2021

### ISSUE THREAD

**Issue by brody2consult** [TrySound/rollup-plugin-size-snapshot#58]
__updated__

- [ ] **highly recommended:** rename default branch to `main`, which would (possibly) affect the branch name for adding GitHub CI workflows
- [ ] add LICENSE file to npm package - __done__ in PR #59
- [ ] test Babel build output - __done__ in PR #59
- [ ] use something like `jest-matcher-deep-close-to` to avoid minor Webpack size variations between Linux, Windows, macOS (etc.)  - __done__ in PR #59 ... ref:
  - https://github.com/facebook/jest/issues/4058#issuecomment-316138505
  - https://github.com/facebook/jest/issues/3654
- [ ] switch from Travis CI to GitHub workflows - __done__ in PR #59
- [ ] **highly recommended:** make Webpack optional as I suggested in https://github.com/TrySound/rollup-plugin-size-snapshot/issues/47#issuecomment-985086426
- [ ] update for recent Webpack v5 release to avoid an issue with Node.js 17  - __done__ in PR #59 ... ref:
  - https://github.com/react-recompose/react-recompose/issues/13
  - https://github.com/webpack/webpack/issues/14532#issuecomment-985083189
  - https://github.com/microsoft/vscode-js-debug/pull/1146
- [ ] update more dependencies
- [ ] address some other issues

I have already got Webpack v5 working in my work area ... and working with Node.js 17, would be happy to work on the other items (except for renaming the default branch) if anyone is interested.
